name: Schedule build deb package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and deploy
      run: ./build.sh

    - name: Archive artifacs
      uses: actions/upload-artifact@v3
      with:
        name: emacs-gcc-pgtk
        path: ./deploy/emacs-gcc-pgtk_*.deb
